### ISSUE TITLE
Should the goweb `import` path include v2?

### ISSUE THREAD

**Issue by matryer** [stretchr/goweb#10]
Should the Goweb import path include the version number?

i.e.

```
import (
  "github.com/stretchrcom/goweb/v2"
)
```

The namespace would still be `goweb` allowing clean code.

**Comment by tylerstillwater** [comment]
Seems to go against go patterns.

It's not our job to manage the version for our users. They can go get -u if they want to update, or checkout a specific tag if they want an older version.

**Comment by matryer** [comment]
Let's put this to the wider Go community and see what they say.  I know http://labix.org/mgo include the version (albeit in a different format)

**Comment by tylerstillwater** [comment]
Sounds good

**Comment by matryer** [comment]
however, it would mean the Goweb version would be:

```
github.com/stretchrcom/goweb/v2/goweb
```

**Comment by matryer** [comment]
... unless we just keep it as `github.com/stretchrcom/goweb/v2` and rely on the package name being properly managed within the code.  This would break convention though wouldn't it?

**Comment by matryer** [comment]
Decided to not do this.
