### ISSUE TITLE
Make Goweb care about the Accept header

### ISSUE THREAD

**Issue by matryer** [stretchr/goweb#20]
Currently JSON is hard coded into Goweb... but the http://github.com/stretchrcom/codecs package supports a content negotiation system, so we should use that.

**Comment by tylerstillwater** [comment]
It sort of does, but it only examines the content type header, not the accept header from the client.

We could add content negotiation to codecs, I suppose?

https://en.wikipedia.org/wiki/Content_negotiation

**Comment by matryer** [comment]
It's already in the codecs package.

Now it's in Goweb too.

Mat
