### ISSUE TITLE
API docs link broken :-(

### ISSUE THREAD

**Issue by matryer** [stretchr/goweb#26]
- see http://godoc.org/github.com/stretchrcom/goweb

**Comment by tylerstillwater** [comment]
Just go to stretchr instead of stretchrcom. It should generate it and work fine. We will need to change the links in read me and whatnot.

**Comment by matryer** [comment]
Fixed.

**Comment by matryer** [comment]
We should check each project

**Comment by tylerstillwater** [comment]
Yes we need to.
