### ISSUE TITLE
Why  Formatter.Format's return value is  []uint8  but []byte?

### ISSUE THREAD

**Issue by tenntenn** [stretchr/goweb#3]
Hi, 
I have a question.
Why  Formatter.Format's return value is  []uint8  but []byte?
http://godoc.org/github.com/stretchrcom/goweb/goweb#Formatter
encoding/json package and other encoding packges use []byte as type of serialized data.

**Comment by matryer** [comment]
This was left over from when the encodings did things differently. Would you like to fix and issue a pull request?

**Comment by tenntenn** [comment]
Thank you for your reply.
OK. I'll fix it.
