### ISSUE TITLE
Collect a list of people using Goweb

### ISSUE THREAD

**Issue by matryer** [stretchr/goweb#40]
We are looking to put together a list of companies / people that are using Goweb.  If you would like to help promote Goweb, and be included in the list, please comment on this issue and we'll get it going.

Thanks,
Goweb team

**Comment by mschlimp** [comment]
Hi,

my name is Marcel. I use the goweb framework for some internal development. So it is used to handle requests for a real time bidding system, handle my website and I also plan to write a framework for go like rails for ruby. For this project I will use goweb for the routing stuff.

Marcel

**Comment by jon-mcmillan** [comment]
Hello,

I represent [MCN Healthcare](http://www.mcnhealthcare.com/) and we are actively developing with Goweb to implement the REST api in-front of a neural network application.

Jon McMillan
Owner MCN Healthcare

(I also want to mention we are doing it the cloud with big data.  Yay I won the internets buzz word competition.)

**Comment by matryer** [comment]
:) great thanks.

**Comment by matryer** [comment]
@dwbuiten what about you? :)

**Comment by dwbuiten** [comment]
@matryer Let me ask legal quickly.

**Comment by matryer** [comment]
Thanks

**Comment by matryer** [comment]
My spin: It's good for companies to show that they're using and contributing to open source projects. << has the advantage of being true too :)

**Comment by dwbuiten** [comment]
I'll let you know tomorrow -- legal is busy today! Such things have been OK'd in the past, so I doubt it's an issue.

**Comment by matryer** [comment]
@dwbuiten any update?  We'd love to brag about you :)

**Comment by dwbuiten** [comment]
@matryer Still waiting on a response from legal... :clock2:

**Comment by dwbuiten** [comment]
@matryer The Lawyer is on vacation until the 19th it seems. Sorry...

**Comment by dwbuiten** [comment]
@matryer And as I said that.. it's been OK'd. Go for it.

**Comment by matryer** [comment]
Great news.  I wonder if you could give us a quote?

**Comment by dwbuiten** [comment]
I'm no PR person... gonna be a bad quote. I'll try.

> Using Goweb has greatly simplified the creation, maintenance, and consistency of several of our internal services, allowing us to focus our effort on the underlying behavior of the services themselves.

Good? I dunno. Communication is hard.

**Comment by rmulley** [comment]
CB Insights is building its API utilizing the GoWeb framework.

http://www.cbinsights.com/developers/api/

**Comment by matryer** [comment]
Thanks guys.

**Comment by oleksandr** [comment]
We're also using Goweb as API server for our tourist/guides application. The name/domain/etc will come later (closer to the pre-beta)

**Comment by matryer** [comment]
Does anyone have anything _nice_ to say about Goweb?

**Comment by rmulley** [comment]
Are you looking for testimonials?  If so I can see if I can get one approved.

**Comment by matryer** [comment]
That'd be great - imagine a Goweb movie poster :-D

**Comment by rmulley** [comment]
How would this testimonial be used?  Just in the documentation or to promote Goweb or elsewhere?

PS: CB Insights is not building the tourist/guides application, looks like the wrong name & link are attached to the testimonial, thanks.

**Comment by matryer** [comment]
@rmulley is it this? http://www.cbinsights.com/

**Comment by dwbuiten** [comment]
@matryer Was what I said not _nice_? :worried:

**Comment by matryer** [comment]
I was hoping for "Goweb saved my life," or "When you've got to go, you've got to Goweb"

```
Not really :)





Actually I wonder if anyone can estimate the time saving they got from using it - that'd be nice. 





Appreciate your help guys

—
```

**Comment by nelsam** [comment]
In my case, at least, I don't think it's possible to estimate.  Not many REST frameworks allow the flexibility that goweb does, so I've traditionally either rolled my own or given up on a solution that is truly REST-compliant.  Goweb (after we added matcherfuncs to MapController) gives me all the flexibility I need to implement a very close approximation of what I understand REST to mean.  Closer than any other framework I've used, in any language.

So in the first case, it saved me from writing my own REST mappers and such, which I'm sure would have been a monstrosity if I tried to write it in Go.  In the second case, it saved me all the back-and-forth of asking how to do something, being told that it's not supported (nor will it be), and eventually just giving up and making a REST-like framework.

Plus, you guys have very clean code.  I learned quite a lot about programming in Go just from browsing the goweb source code.

**Comment by dwbuiten** [comment]
I probably could not estimate it as well... I have nothing to compare to realistically.

**Comment by rmulley** [comment]
@matryer Yes that is the link

**Comment by nelsam** [comment]
By the way, I didn't mention this before:  In addition to using goweb for our AI project at MCN Healthcare (as mentioned by my boss, Jon McMillan), I'm using goweb for many of my other projects.  I enjoy writing in Go, and goweb gets the boring stuff done quickly so I can focus on the fun parts.
