### ISSUE TITLE
always200 & method overriding for API responder?

### ISSUE THREAD

**Issue by oleksandr** [stretchr/goweb#45]
This one comes from your front-end developers complaining (as usually) about support of all HTTP by some browsers. Does it makes sense to add these features to the API responder?

**Comment by matryer** [comment]
Front end developers are my favourite - one of the reasons we built Goweb was to make your lives easier. 

Always200 and the method override are actually implemented in the WebContext object. 

How would they work in the API Responder?

**Comment by oleksandr** [comment]
Sorry for the confusing message yesterday - that was EOD :-) Well, the front end devs asked about emulation of the HTTP methods, in other words they want to send
POST /uri?method=PUT&... instead of PUT /uri?...
POST /uri?method=DELETE&... instead of DELETE /uri?...
I was looking into the goweb's docs and source code and couldn't find this implemented. But I remember that v1.0 (that we started from) had this feature.

Am I blind or was it dropped in v2.0?

Thanks!

**Comment by matryer** [comment]
It's there - 

Do we need to update the docs?

**Comment by tylerstillwater** [comment]
Please see the `WithStatus` method in http://godoc.org/github.com/stretchr/goweb/responders for the `always200` info.
Please see the `MethodString` method in http://godoc.org/github.com/stretchr/goweb/webcontext for the `method` override info.
Please see "Working with JSONP" in http://godoc.org/github.com/stretchr/goweb for usage.
