### ISSUE TITLE
Unable to pass in a URL as a parameter

### ISSUE THREAD

**Issue by rmulley** [stretchr/goweb#5]
For example if I wanted to pass in stripe.com in a url like:

www.example.com/api/company/stripe.com/info

And listener was setup as such:

``` Go
goweb.MapFunc("/api/company/{company}/info/", func(c *goweb.Context) {
    fmt.Println(c.PathParams["company"])
}) //goweb.MapFunc
```

I get "stripe" printed out, instead of "stripe.com"

**Comment by matryer** [comment]
OK this test now passes: https://github.com/stretchrcom/goweb/commit/32a2159d3b04be1c1f5b1857afee65d184136355#L1R27

Please confirm and close.

**Comment by rmulley** [comment]
Thanks for the quick fix, looks great.

**Comment by matryer** [comment]
Why did this get reverted?

**Comment by dwa012** [comment]
There was a bad commit. I went back to fix it. The issue should not have been referenced.
