### ISSUE TITLE
Support `***/something` paths

### ISSUE THREAD

**Issue by matryer** [stretchr/goweb#53]
Allow wildcard prefixes in paths.

**Comment by matryer** [comment]
We should also support paths like these:

Any path that contains the `people` segment:
    \* \* \* _/people/_ \* \* \* 

Any path that contians `something`, then 0-x number of path segments, then an ending `else` segment.
    \* \* \* _/something/_ \* \* */else

NOTE: \* \* \* has spaces to prevent formatting

**Comment by matryer** [comment]
Started in branch `issues/53`

**Comment by matryer** [comment]
This is tricky - @tylerb fancy having a go?

**Comment by tylerstillwater** [comment]
I'll look at it.

**Comment by matryer** [comment]
I tried to nail this but it was too hard :(

**Comment by tylerstillwater** [comment]
.... that's what she said?

**Comment by matryer** [comment]
+1 point for @tylerb
