### ISSUE TITLE
Support for PATCH

### ISSUE THREAD

**Issue by vayam** [stretchr/goweb#57]
Will you be adding support for [`PATCH`](http://tools.ietf.org/html/rfc5789)?

**Comment by matryer** [comment]
Technically you can do this today:

```
goweb.Map("PATCH", "resource/1", func(c context.Context) {
  // ...
})
```

Do you mean in the controllers?

**Comment by vayam** [comment]
controller would have be nice. but this works too. thanks.

**Comment by matryer** [comment]
@vayam - I actually agree... please give me your feedback here: https://github.com/stretchr/goweb/issues/58

**Comment by matryer** [comment]
Please see https://github.com/stretchr/goweb/pull/60
