### ISSUE TITLE
RestfulManyUpdater has wrong mapping

### ISSUE THREAD

**Issue by pengux** [stretchr/goweb#62]
In the docs (http://godoc.org/github.com/stretchr/goweb/controllers#RestfulManyUpdater), the RestfulManyUpdater has this mapping:

GET /resources/{id}

Which is not correct and should instead be:

PUT /resources

I haven't check if it is only an error in documentation or if the implementation is incorrect also

**Comment by nelsam** [comment]
Yep, that documentation is wrong.

For the time being, I did a quick check - RestfulManyUpdater is correct in the code (see: https://github.com/stretchr/goweb/blob/master/handlers/mapping.go#L288), so it's safe to use.  It's only the documentation that's screwed up.

**Comment by pengux** [comment]
I also saw this issue after posting

https://github.com/stretchr/goweb/pull/60

does this mean that it is a PATCH method for RestfulManyUpdater now?

**Comment by nelsam** [comment]
That pull request hasn't been merged, yet, so those changes are not yet in the code.  Currently, it's using PUT, not PATCH.

**Comment by matryer** [comment]
Is this fixed now?  Can someone close this issue?

**Comment by matryer** [comment]
Closing issue as it seems to be fixed.
