### ISSUE TITLE
Don't envelop data in responses by default

### ISSUE THREAD

**Issue by pengux** [stretchr/goweb#63]
HI,

maybe I'm missing something but I can't find any obvious way to turn off enveloping of data in responses (http://godoc.org/github.com/stretchr/goweb/responders#pkg-constants)

Data enveloping should not be default (http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#envelope) but rather let the API creator decide whether to support it or not.

**Comment by nelsam** [comment]
I had the same issue. Try goweb.API.WriteResponseObject. It takes the context.Context value passed to your handler, the HTTP status, and a value to be converted by the requested codec.

**Comment by matryer** [comment]
Yes I agree actually - and there is also a transformer for the response object that you can use to unwrap it. 

Essentially just return the "d" value.

**Comment by pengux** [comment]
Would you accept a PR to fix the RespondWithData() so it takes into consideration a ?envelop=true parameter or forcing enveloping by passing a third parameter to it before it envelop the response data?

**Comment by matryer** [comment]
I’m not sure a parameter is the right place for this - instead, maybe it’s a setting:

```
goweb.EnvelopeResponse = false
```

Mat

**Comment by pengux** [comment]
The GET parameter allows the client to request enveloping the data if
required. It's necessary for example JSONP

2013/11/3 Mat Ryer notifications@github.com

> I’m not sure a parameter is the right place for this - instead, maybe it’s
> a setting:
> 
> goweb.EnvelopeResponse = false
> 
> Mat
>

**Comment by matryer** [comment]
Good point - maybe we do both then?

```
// AlwaysEnvelopeResponse tells Goweb whether to envelope the response 
// or not.  Default = true (has to be true because of existing code)
goweb.AlwaysEnvelopeResponse = false
```

AND we'll let clients specify with:

```
GET /something?envelope=true
```

Sound good?  If so, do you fancy submitting a PR?  If so, please give TDD a go, it's pretty cool in Go.

**Comment by matryer** [comment]
see https://github.com/stretchr/goweb/wiki/Development-practices

**Comment by pengux** [comment]
Do you mean to use TDD for the PR? Yes, I can do that. I'll try to submit
it during this weekend

MVH

Peter

_Chief Technology Officer_ @ Likipe Digital
Website: http://likipe.se
Phone: +4633418434

2013/11/5 Mat Ryer notifications@github.com

**Comment by matryer** [comment]
Great - I look forward to it.
