### ISSUE TITLE
Body is empty with GET request

### ISSUE THREAD

**Issue by dwa012** [stretchr/goweb#7]
I am trying to send some JSON data to a GET request. The body is empty, even though I am transmitting some. It works fine for POST actions

EDIT:
Seems to be working now. I think it was whatever tool I was using to send the request

**Comment by matryer** [comment]
GET requests do not support bodies.  Consider following RESTful patterns. 

Hope this helps
Mat

**Comment by dwa012** [comment]
My apologies. I am still new with working with web protocols in this fashion.

**Comment by matryer** [comment]
Not a problem - let us know if you have any more questions.
