### ISSUE TITLE
Gzip Compression

### ISSUE THREAD

**Issue by nemosupremo** [stretchr/goweb#73]
Is there a kosher way of adding gzip compressed responses to goweb?

**Comment by tobz** [comment]
You could instantiate the HTTP handler (handlers.HttpHandler) object yourself, and use something like this to wrap it: http://nf.id.au/posts/2011/04/roll-your-own-gzip-encoded-http-handler.html

**Comment by tobz** [comment]
It also bears mentioning, though: if you're developing a secure site with that this, you're potentially opening yourself up to the BREACH attack by using compression and SSL together.  It depends on a number of circumstances, though, which you could prime yourself on at: http://breachattack.com/

**Comment by nemosupremo** [comment]
Okay, thanks.
