### ISSUE TITLE
Over-eager path matching

### ISSUE THREAD

**Issue by matryer** [stretchr/goweb#77]
This path: 

```
/people/{people}/***
```

is matching:

```
/people
```

Where it shouldn't be.

**Comment by tylerstillwater** [comment]
Weird. Is this a regex thing? If so I can look at it.

**Comment by matryer** [comment]
I’ve fixed it for now… but I think we should rewrite the path matching stuff in Goweb to use RegEx.  It’s better designed.  Let’s look at it.
