### ISSUE TITLE
why "/" is generate error?

### ISSUE THREAD

**Issue by Nipol** [stretchr/goweb#8]
func main() {

```
goweb.MapFunc("/", func(c *goweb.Context) {
    t, _ := template.ParseFiles("html/index.html")
    t.Execute(c.ResponseWriter, nil)
})

goweb.MapFunc("/user", func(c *goweb.Context) {
    fmt.Println(c.Request.FormValue("id"))
    fmt.Println(c.Request.FormValue("pass"))
})

goweb.ListenAndServe(":8080")
```

}

root page is

"Oops, something went wrong: No route found for that path"

why not working?
my eye's in Red on inside every code
i don't know that.
help me

**Comment by matryer** [comment]
Have you tried "" instead of "/"?  Slashes are trimmed.

**Comment by Nipol** [comment]
I tried not worked......I have access root / generated same error!
and access '/user' generated print out index.html
why not worked?...... simplify trimmed not problem. i think.

**Comment by matryer** [comment]
Try

```
goweb.Map("*"...
```

And put it at the END.

**Comment by matryer** [comment]
... or better still, get Goweb v2 from here: https://github.com/stretchrcom/goweb/tree/v2

**Comment by matryer** [comment]
This is fixed in Goweb 2
