### ISSUE TITLE
BeforeHandler.Before() where are errors returned to?

### ISSUE THREAD

**Issue by tgreiser** [stretchr/goweb#83]
On a controller, if Before() returns an error, where does that error go? If I do this I get an error/debug HTML page that looks like it's generated by goweb (in response to a JSON API request).

func (controller *SecureController) Before(ctx context.Context) error {
  if controller.Authenticate() == false {
    return errors.New("Authentication failed")
  }
  return nil
}

I want to handle this authentication error myself, but I'm not sure how or where I should go about that.

<!DOCTYPE html>
<html>
    <head>
        <style>h1 { font-size: 17px }h1 strong {text-decoration:underline}h2 { background-color: #ffd; padding: 20px }footer { margin-top: 20px; border-top:1px solid black; padding:10px; font-size:0.9em }</style>
    </head>
    <body>
        <h1>Error in 
            <code>PATCH|OPTIONS users/{id} - 0x81c9070 
</code>
        </h1>
        <h2>Failed authentication</h2>
        <h3>
            <code>*errors.errorString</code> error in Handler 
            <code>0x18b78830</code>
        </h3>
        <code>
            <pre>PATCH|OPTIONS users/{id} - 0x81c9070 
</pre>
        </code>on adminuser-VirtualBox
        <footer>Learn more about 
            <a href='http://github.com/stretchr/goweb' target='_blank'>Goweb</a>
        </footer>
    </body>
</html>

**Comment by matryer** [comment]
You can use [SetErrorHandler](http://godoc.org/github.com/stretchr/goweb/handlers#HttpHandler.SetErrorHandler) to explicitly handle errors yourself.

**Comment by matryer** [comment]
FYI - the DefaultErrorHandler is what writes that error page out - see https://github.com/stretchr/goweb/blob/master/handlers/default_error_handler.go#L24

**Comment by tgreiser** [comment]
Thank you!
