### ISSUE TITLE
putting controllers in different files

### ISSUE THREAD

**Issue by yvz5** [stretchr/goweb#87]
hey all,

great project, but im totally new to go and i want to make a RESTful webservice which outputs json results from my mysql database. i've been using PHP lately and its a bit complicated for me to switch over to go. 

so my problem is, i want to be able to put the controller in different files in the sake of having clear structure of codes. and of course, if you could give me an example of how to do a controller-model structure, that would be amazing.

keep up the good work guys, this is promising.

**Comment by matryer** [comment]
Goweb is a Go project, not D. You should try Go - you'll love it.

**Comment by yvz5** [comment]
Sorry i typed in wrong. Im using go. So far i got it Wirkung with different files in different packages.
