### ISSUE TITLE
MapFunc matching all substrings  

### ISSUE THREAD

**Issue by Nican** [stretchr/goweb#9]
I am having an issue such that MapFunc is matching anything with the sub string of the path. For example:  

```
goweb.MapFunc("/a", serverA)
goweb.MapFunc("/nota", serverB)
```

And any page containing "a" will call serverA, including "localhost:8080/nota", and for example, "localhost:8080/ishouldbe404a" is also calling serveA.

**Comment by matryer** [comment]
Yes - this is fixed in Goweb 2 (the v2 branch) but its not 100% ready. Meanwhile, be more specific first (I.e switch them around)

**Comment by matryer** [comment]
UPDATE: Goweb 2 is ready... and your code will work properly if you use it.

**Comment by matryer** [comment]
This is fixed in Goweb 2
